/*
Name: Hugo David Franco Avila
Date: 22 - March - 2018
This class shows the interface for the Pokemon game
 */

import pokemongame.*;

public class PokeGUI extends javax.swing.JFrame {
    
    int count = 0;//counter to see whose turn is it
    boolean z = false, x = false, y = false;//this variables will help as flags
    /*Creation of pokemon objects*/
    Pokemon pikachu = new ElectricPokemon("Pikachu");
    Pokemon voltorb = new ElectricPokemon("Voltorb");
    Pokemon vaporeon = new WaterPokemon("Vaporeon");
    Pokemon squirtle = new WaterPokemon("Squirtle");
    Pokemon flareon = new FirePokemon("Flareon");
    Pokemon charizard = new FirePokemon("Charizard");
    Player[] player = new Player[2];//creation of player array

    /**
     * Creates new form PokeGUI
     */
    public PokeGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainUI = new javax.swing.JPanel();
        play = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        mainImage = new javax.swing.JLabel();
        winUI = new javax.swing.JPanel();
        grats = new javax.swing.JTextField();
        wPlayer = new javax.swing.JTextField();
        won = new javax.swing.JTextField();
        mainButton = new javax.swing.JButton();
        BattleUI = new javax.swing.JPanel();
        lightAttackButton = new javax.swing.JButton();
        heavyAttackButton = new javax.swing.JButton();
        sPokButton = new javax.swing.JButton();
        forfeitButton = new javax.swing.JButton();
        player1Poke = new javax.swing.JTextField();
        player1PokeType = new javax.swing.JTextField();
        player1HP = new javax.swing.JTextField();
        player2Poke = new javax.swing.JTextField();
        player2PokeType = new javax.swing.JTextField();
        player2HP = new javax.swing.JTextField();
        Player20 = new javax.swing.JLabel();
        Player10 = new javax.swing.JLabel();
        Player225 = new javax.swing.JLabel();
        Player125 = new javax.swing.JLabel();
        Player250 = new javax.swing.JLabel();
        Player150 = new javax.swing.JLabel();
        Player175 = new javax.swing.JLabel();
        Player275 = new javax.swing.JLabel();
        Player2Squirtle = new javax.swing.JLabel();
        Player1Squirtle = new javax.swing.JLabel();
        Player2Vaporeon = new javax.swing.JLabel();
        Player1Vaporeon = new javax.swing.JLabel();
        Player2Flareon = new javax.swing.JLabel();
        Player1Flareon = new javax.swing.JLabel();
        Player2Voltorb = new javax.swing.JLabel();
        Player1Voltorb = new javax.swing.JLabel();
        Player2Pikachu = new javax.swing.JLabel();
        Player1Pikachu = new javax.swing.JLabel();
        Player2Charizard = new javax.swing.JLabel();
        Player1Charizard = new javax.swing.JLabel();
        follow = new javax.swing.JPanel();
        pokeName = new javax.swing.JTextField();
        used = new javax.swing.JTextField();
        typeAttack = new javax.swing.JTextField();
        effective = new javax.swing.JTextField();
        followOK = new javax.swing.JButton();
        playerTurn = new javax.swing.JTextField();
        currentPoke = new javax.swing.JTextField();
        mainBattle = new javax.swing.JLabel();
        PokeSelectUI = new javax.swing.JPanel();
        PikaButton = new javax.swing.JButton();
        VoltButton = new javax.swing.JButton();
        CharButton = new javax.swing.JButton();
        FlarButton = new javax.swing.JButton();
        SquButton = new javax.swing.JButton();
        VapoButton = new javax.swing.JButton();
        select = new javax.swing.JTextField();
        okSelect = new javax.swing.JButton();
        pTurn = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);

        mainUI.setBackground(new java.awt.Color(0, 255, 204));
        mainUI.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        play.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        play.setText("Play");
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });
        mainUI.add(play, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 460, 198, 85));

        exit.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        mainUI.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 580, 198, 85));

        mainImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Code6/Pokemon.png"))); // NOI18N
        mainUI.add(mainImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 1210, -1));

        winUI.setBackground(new java.awt.Color(0, 255, 204));

        grats.setEditable(false);
        grats.setBackground(new java.awt.Color(0, 255, 204));
        grats.setFont(new java.awt.Font("Consolas", 1, 48)); // NOI18N
        grats.setText("Congratulations");
        grats.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        wPlayer.setEditable(false);
        wPlayer.setBackground(new java.awt.Color(0, 255, 204));
        wPlayer.setFont(new java.awt.Font("Consolas", 1, 48)); // NOI18N
        wPlayer.setText("PLAYER 1");
        wPlayer.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        won.setEditable(false);
        won.setBackground(new java.awt.Color(0, 255, 204));
        won.setFont(new java.awt.Font("Consolas", 1, 48)); // NOI18N
        won.setText("you won!");
        won.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        mainButton.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        mainButton.setText("Exit");
        mainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout winUILayout = new javax.swing.GroupLayout(winUI);
        winUI.setLayout(winUILayout);
        winUILayout.setHorizontalGroup(
            winUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(winUILayout.createSequentialGroup()
                .addGroup(winUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(winUILayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(grats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(winUILayout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addGroup(winUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(winUILayout.createSequentialGroup()
                                .addComponent(won, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(mainButton))
                            .addComponent(wPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 269, Short.MAX_VALUE))
        );
        winUILayout.setVerticalGroup(
            winUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(winUILayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(grats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(wPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(winUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(winUILayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(won, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(winUILayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(mainButton)))
                .addContainerGap(199, Short.MAX_VALUE))
        );

        mainUI.add(winUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, -1, -1));
        winUI.setVisible(false);

        BattleUI.setBackground(new java.awt.Color(0, 255, 204));
        BattleUI.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lightAttackButton.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        lightAttackButton.setText("LIGHT ATTACK");
        lightAttackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lightAttackButtonActionPerformed(evt);
            }
        });
        BattleUI.add(lightAttackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 560, -1, -1));

        heavyAttackButton.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        heavyAttackButton.setText("HEAVY ATTACK");
        heavyAttackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heavyAttackButtonActionPerformed(evt);
            }
        });
        BattleUI.add(heavyAttackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 560, -1, -1));

        sPokButton.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        sPokButton.setText("POKéMON");
        sPokButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sPokButtonActionPerformed(evt);
            }
        });
        BattleUI.add(sPokButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 620, 140, 30));

        forfeitButton.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        forfeitButton.setText("FORFEIT");
        forfeitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forfeitButtonActionPerformed(evt);
            }
        });
        BattleUI.add(forfeitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 620, 140, 30));

        player1Poke.setEditable(false);
        player1Poke.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        player1Poke.setText("SQUIRTLE");
        player1Poke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player1PokeActionPerformed(evt);
            }
        });
        BattleUI.add(player1Poke, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 150, -1));

        player1PokeType.setEditable(false);
        player1PokeType.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        player1PokeType.setText("WATER");
        BattleUI.add(player1PokeType, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 110, -1));

        player1HP.setEditable(false);
        player1HP.setText("100%");
        player1HP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player1HPActionPerformed(evt);
            }
        });
        BattleUI.add(player1HP, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, -1, -1));

        player2Poke.setEditable(false);
        player2Poke.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        player2Poke.setText("CHARIZARD");
        player2Poke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player2PokeActionPerformed(evt);
            }
        });
        BattleUI.add(player2Poke, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 440, 150, -1));

        player2PokeType.setEditable(false);
        player2PokeType.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        player2PokeType.setText("FIRE");
        BattleUI.add(player2PokeType, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 440, 130, -1));

        player2HP.setEditable(false);
        player2HP.setText("100%");
        BattleUI.add(player2HP, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 400, -1, -1));

        Player20.setIcon(new javax.swing.ImageIcon("C:\\ProgramasITC\\2doSem\\OOP\\code6\\PokemonGame\\build\\classes\\Code6\\HealthBar0.png")); // NOI18N
        BattleUI.add(Player20, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, -1, -1));
        Player20.setVisible(false);

        Player10.setIcon(new javax.swing.ImageIcon("C:\\ProgramasITC\\2doSem\\OOP\\code6\\PokemonGame\\build\\classes\\Code6\\HealthBar0.png")); // NOI18N
        BattleUI.add(Player10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));
        Player10.setVisible(false);

        Player225.setIcon(new javax.swing.ImageIcon("C:\\ProgramasITC\\2doSem\\OOP\\code6\\PokemonGame\\build\\classes\\Code6\\HealthBar25.png")); // NOI18N
        BattleUI.add(Player225, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, -1, -1));
        Player225.setVisible(false);

        Player125.setIcon(new javax.swing.ImageIcon("C:\\ProgramasITC\\2doSem\\OOP\\code6\\PokemonGame\\build\\classes\\Code6\\HealthBar25.png")); // NOI18N
        BattleUI.add(Player125, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));
        Player125.setVisible(false);

        Player250.setIcon(new javax.swing.ImageIcon("C:\\ProgramasITC\\2doSem\\OOP\\code6\\PokemonGame\\build\\classes\\Code6\\HealthBar50.png")); // NOI18N
        BattleUI.add(Player250, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, -1, -1));
        Player250.setVisible(false);

        Player150.setIcon(new javax.swing.ImageIcon("C:\\ProgramasITC\\2doSem\\OOP\\code6\\PokemonGame\\build\\classes\\Code6\\HealthBar50.png")); // NOI18N
        BattleUI.add(Player150, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));
        Player150.setVisible(false);

        Player175.setIcon(new javax.swing.ImageIcon("C:\\ProgramasITC\\2doSem\\OOP\\code6\\PokemonGame\\build\\classes\\Code6\\HealthBar75.png")); // NOI18N
        BattleUI.add(Player175, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));
        Player175.setVisible(false);

        Player275.setIcon(new javax.swing.ImageIcon("C:\\ProgramasITC\\2doSem\\OOP\\code6\\PokemonGame\\build\\classes\\Code6\\HealthBar75.png")); // NOI18N
        BattleUI.add(Player275, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, -1, -1));
        Player275.setVisible(false);

        Player2Squirtle.setIcon(new javax.swing.ImageIcon("C:\\ProgramasITC\\2doSem\\OOP\\code6\\PokemonGame\\build\\classes\\Code6\\squirtlebattle2.png")); // NOI18N
        BattleUI.add(Player2Squirtle, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));
        Player2Squirtle.setVisible(false);

        Player1Squirtle.setIcon(new javax.swing.ImageIcon("C:\\ProgramasITC\\2doSem\\OOP\\code6\\PokemonGame\\build\\classes\\Code6\\squirtlebattle1.png")); // NOI18N
        BattleUI.add(Player1Squirtle, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, -1, -1));
        Player1Squirtle.setVisible(false);

        Player2Vaporeon.setIcon(new javax.swing.ImageIcon("C:\\ProgramasITC\\2doSem\\OOP\\code6\\PokemonGame\\build\\classes\\Code6\\vapo2.png")); // NOI18N
        BattleUI.add(Player2Vaporeon, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, -1, -1));
        Player2Vaporeon.setVisible(false);

        Player1Vaporeon.setIcon(new javax.swing.ImageIcon("C:\\ProgramasITC\\2doSem\\OOP\\code6\\PokemonGame\\build\\classes\\Code6\\Vapobattle1.png")); // NOI18N
        BattleUI.add(Player1Vaporeon, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, 300, 300));
        Player1Vaporeon.setVisible(false);

        Player2Flareon.setIcon(new javax.swing.ImageIcon("C:\\ProgramasITC\\2doSem\\OOP\\code6\\PokemonGame\\build\\classes\\Code6\\flareonbattle2.png")); // NOI18N
        BattleUI.add(Player2Flareon, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));
        Player2Flareon.setVisible(false);

        Player1Flareon.setIcon(new javax.swing.ImageIcon("C:\\ProgramasITC\\2doSem\\OOP\\code6\\PokemonGame\\build\\classes\\Code6\\flareonbattle1.png")); // NOI18N
        BattleUI.add(Player1Flareon, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, -1, -1));
        Player1Flareon.setVisible(false);

        Player2Voltorb.setIcon(new javax.swing.ImageIcon("C:\\ProgramasITC\\2doSem\\OOP\\code6\\PokemonGame\\build\\classes\\Code6\\Volt.png")); // NOI18N
        BattleUI.add(Player2Voltorb, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));
        Player2Voltorb.setVisible(false);

        Player1Voltorb.setIcon(new javax.swing.ImageIcon("C:\\ProgramasITC\\2doSem\\OOP\\code6\\PokemonGame\\build\\classes\\Code6\\VoltorbBatlle1.png")); // NOI18N
        BattleUI.add(Player1Voltorb, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, -1, -1));
        Player1Voltorb.setVisible(false);

        Player2Pikachu.setIcon(new javax.swing.ImageIcon("C:\\ProgramasITC\\2doSem\\OOP\\code6\\PokemonGame\\build\\classes\\Code6\\Pikabattle2.jpg")); // NOI18N
        BattleUI.add(Player2Pikachu, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));
        Player2Pikachu.setVisible(false);

        Player1Pikachu.setIcon(new javax.swing.ImageIcon("C:\\ProgramasITC\\2doSem\\OOP\\code6\\PokemonGame\\build\\classes\\Code6\\Pikabattle1.jpg")); // NOI18N
        BattleUI.add(Player1Pikachu, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, -1, -1));
        Player1Pikachu.setVisible(false);

        Player2Charizard.setIcon(new javax.swing.ImageIcon("C:\\ProgramasITC\\2doSem\\OOP\\code6\\PokemonGame\\build\\classes\\Code6\\CharBattle.png")); // NOI18N
        BattleUI.add(Player2Charizard, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 330, 190));
        Player2Charizard.setVisible(false);

        Player1Charizard.setIcon(new javax.swing.ImageIcon("C:\\ProgramasITC\\2doSem\\OOP\\code6\\PokemonGame\\build\\classes\\Code6\\CharBattle1.jpg")); // NOI18N
        BattleUI.add(Player1Charizard, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, -1, -1));
        Player1Charizard.setVisible(false);

        follow.setBackground(new java.awt.Color(0, 4, 145));

        pokeName.setEditable(false);
        pokeName.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        pokeName.setText("SQUIRTLE");

        used.setEditable(false);
        used.setBackground(new java.awt.Color(0, 4, 154));
        used.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        used.setForeground(new java.awt.Color(255, 255, 255));
        used.setText("used");
        used.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        typeAttack.setEditable(false);
        typeAttack.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        typeAttack.setText("LIGHT ATTACK");

        effective.setEditable(false);
        effective.setBackground(new java.awt.Color(0, 4, 154));
        effective.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        effective.setForeground(new java.awt.Color(255, 255, 255));
        effective.setText("It's super effective!");
        effective.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        followOK.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        followOK.setText("OK");
        followOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                followOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout followLayout = new javax.swing.GroupLayout(follow);
        follow.setLayout(followLayout);
        followLayout.setHorizontalGroup(
            followLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(followLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(followLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(followLayout.createSequentialGroup()
                        .addComponent(effective, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(followOK))
                    .addGroup(followLayout.createSequentialGroup()
                        .addComponent(pokeName, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(used, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(typeAttack, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        followLayout.setVerticalGroup(
            followLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(followLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(followLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pokeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(used, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeAttack, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(followLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(followLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(effective, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(39, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, followLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(followOK)
                        .addContainerGap())))
        );

        BattleUI.add(follow, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 490, 150));
        follow.setVisible(false);

        playerTurn.setEditable(false);
        playerTurn.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        playerTurn.setText("Player 1");
        BattleUI.add(playerTurn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 130, 40));

        currentPoke.setEditable(false);
        currentPoke.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        currentPoke.setText("SQUIRTLE");
        currentPoke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentPokeActionPerformed(evt);
            }
        });
        BattleUI.add(currentPoke, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 630, 260, -1));

        mainBattle.setBackground(new java.awt.Color(0, 0, 105));
        mainBattle.setIcon(new javax.swing.ImageIcon("C:\\ProgramasITC\\2doSem\\OOP\\code6\\PokemonGame\\build\\classes\\Code6\\Poke.png")); // NOI18N
        BattleUI.add(mainBattle, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 16, -1, -1));

        mainUI.add(BattleUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 1440, 700));
        BattleUI.setVisible(false);

        PokeSelectUI.setBackground(new java.awt.Color(0, 255, 204));

        PikaButton.setIcon(new javax.swing.ImageIcon("C:\\ProgramasITC\\2doSem\\OOP\\code6\\PokemonGame\\build\\classes\\Code6\\Pikachu.png")); // NOI18N
        PikaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PikaButtonActionPerformed(evt);
            }
        });

        VoltButton.setIcon(new javax.swing.ImageIcon("C:\\ProgramasITC\\2doSem\\OOP\\code6\\PokemonGame\\build\\classes\\Code6\\Voltorb.png")); // NOI18N
        VoltButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltButtonActionPerformed(evt);
            }
        });

        CharButton.setIcon(new javax.swing.ImageIcon("C:\\ProgramasITC\\2doSem\\OOP\\code6\\PokemonGame\\build\\classes\\Code6\\Charizard.png")); // NOI18N
        CharButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CharButtonActionPerformed(evt);
            }
        });

        FlarButton.setIcon(new javax.swing.ImageIcon("C:\\ProgramasITC\\2doSem\\OOP\\code6\\PokemonGame\\build\\classes\\Code6\\Flareon.png")); // NOI18N
        FlarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlarButtonActionPerformed(evt);
            }
        });

        SquButton.setIcon(new javax.swing.ImageIcon("C:\\ProgramasITC\\2doSem\\OOP\\code6\\PokemonGame\\build\\classes\\Code6\\Squirtle.png")); // NOI18N
        SquButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SquButtonActionPerformed(evt);
            }
        });

        VapoButton.setIcon(new javax.swing.ImageIcon("C:\\ProgramasITC\\2doSem\\OOP\\code6\\PokemonGame\\build\\classes\\Code6\\Vaporeon.png")); // NOI18N
        VapoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VapoButtonActionPerformed(evt);
            }
        });

        select.setEditable(false);
        select.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        select.setText("Select Pokemon");
        select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectActionPerformed(evt);
            }
        });

        okSelect.setBackground(new java.awt.Color(0, 0, 153));
        okSelect.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        okSelect.setForeground(new java.awt.Color(255, 255, 255));
        okSelect.setText("OK");
        okSelect.setToolTipText("");
        okSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okSelectActionPerformed(evt);
            }
        });

        pTurn.setEditable(false);
        pTurn.setBackground(new java.awt.Color(0, 255, 204));
        pTurn.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        pTurn.setText("PLAYER 1");
        pTurn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout PokeSelectUILayout = new javax.swing.GroupLayout(PokeSelectUI);
        PokeSelectUI.setLayout(PokeSelectUILayout);
        PokeSelectUILayout.setHorizontalGroup(
            PokeSelectUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PokeSelectUILayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addGroup(PokeSelectUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pTurn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PokeSelectUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(PokeSelectUILayout.createSequentialGroup()
                            .addComponent(SquButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(VapoButton))
                        .addGroup(PokeSelectUILayout.createSequentialGroup()
                            .addComponent(CharButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FlarButton))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PokeSelectUILayout.createSequentialGroup()
                            .addComponent(PikaButton)
                            .addGap(109, 109, 109)
                            .addComponent(VoltButton)))
                    .addGroup(PokeSelectUILayout.createSequentialGroup()
                        .addComponent(select, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117)
                        .addComponent(okSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(597, Short.MAX_VALUE))
        );
        PokeSelectUILayout.setVerticalGroup(
            PokeSelectUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PokeSelectUILayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(PokeSelectUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PikaButton)
                    .addComponent(VoltButton))
                .addGap(39, 39, 39)
                .addGroup(PokeSelectUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CharButton)
                    .addComponent(FlarButton))
                .addGap(41, 41, 41)
                .addGroup(PokeSelectUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VapoButton)
                    .addComponent(SquButton))
                .addGap(29, 29, 29)
                .addComponent(pTurn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PokeSelectUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(select, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(okSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        mainUI.add(PokeSelectUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 700));
        PokeSelectUI.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainUI, javax.swing.GroupLayout.PREFERRED_SIZE, 1438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainUI, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);//Exit the program
    }//GEN-LAST:event_exitActionPerformed

    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        // TODO add your handling code here:
       exit.setVisible(false);
       play.setVisible(false);
       mainImage.setVisible(false);
       /*Main UI components get hidden and selectUI appears.
       Players get created with default attributes
       */
       PokeSelectUI.setVisible(true);
       player[0] = new Player("Player 1", pikachu);
       player[1] = new Player("Player 2", pikachu);
       
       
       

    }//GEN-LAST:event_playActionPerformed

    private void selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_selectActionPerformed

    private void okSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okSelectActionPerformed
        
        //count++;
        if(x){
            count--;//This helps me avoid an issue when I'm changng Pokemon
                    //in the middle of the fight
        }
        if (z){
            /*both players have made their starting pick*/
            PokeSelectUI.setVisible(false);
            BattleUI.setVisible(true);
            x = true;
        } else{
            /*will only enter this part once, so player 2 can pick his pokemon*/
            pTurn.setText("PLAYER 2");
            select.setText("Select your pokemon");
            z = true;
            count++;
        }
    }//GEN-LAST:event_okSelectActionPerformed

    /*This function enters the selectUI menu whenever the user wants to 
    change his pokemon in the middle of a fight. The button disables itself
    so it can't be abused by a player
    */
    private void sPokButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sPokButtonActionPerformed
        // TODO add your handling code here:
        count++;
        y = true;
        PokeSelectUI.setVisible(true);
        BattleUI.setVisible(false);
        pTurn.setText("Player " + (count%2 + 1));
        sPokButton.setEnabled(false);
       
    }//GEN-LAST:event_sPokButtonActionPerformed

    /*This button exists if any player wants to give up before he is defeated*/
    private void forfeitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forfeitButtonActionPerformed
        // TODO add your handling code here:
        count++;
        player[count%2].setHealth(0);//player loses all his health
        pokeName.setText(player[count%2].pName());
        used.setText("has");
        typeAttack.setText("forfeited");
        effective.setText("He is fleeing the fight!");
        /*Disabling buttons*/
        lightAttackButton.setEnabled(false);
        heavyAttackButton.setEnabled(false);
        sPokButton.setEnabled(false);
        forfeitButton.setEnabled(false);
        follow.setVisible(true);  
    }//GEN-LAST:event_forfeitButtonActionPerformed

    private void player1PokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player1PokeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_player1PokeActionPerformed

    private void player2PokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player2PokeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_player2PokeActionPerformed

    private void currentPokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentPokeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentPokeActionPerformed

    private void mainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);//Exit after the game has ended
    }//GEN-LAST:event_mainButtonActionPerformed
    
    /*This button makes the selection of pikachu and changes every icon to
    reflect our choice
    */
    private void PikaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PikaButtonActionPerformed
        // TODO add your handling code here:
        select.setText("Pikachu");
        player[count%2].setPokemon(pikachu);
        if(count%2 == 0){
            Player1Pikachu.setVisible(true);
            Player1Voltorb.setVisible(false);
            Player1Vaporeon.setVisible(false);
            Player1Squirtle.setVisible(false);
            Player1Flareon.setVisible(false);
            Player1Charizard.setVisible(false);
            player1Poke.setText("Pikachu");
            player1PokeType.setText("Electric");
            currentPoke.setText("Pikachu");
        }
        
        if(count%2 == 1 ){
            Player2Pikachu.setVisible(true);
            Player2Voltorb.setVisible(false);
            Player2Vaporeon.setVisible(false);
            Player2Squirtle.setVisible(false);
            Player2Flareon.setVisible(false);
            Player2Charizard.setVisible(false);
            player2Poke.setText("Pikachu");
            player2PokeType.setText("Electric");
            if(y){//special flag for when player is in the middle of a game
                currentPoke.setText("Pikachu"); 
            }
        }
    }//GEN-LAST:event_PikaButtonActionPerformed
    
    /*This button makes the selection of voltorb and changes every icon to
    reflect our choice
    */
    private void VoltButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltButtonActionPerformed
        // TODO add your handling code here:
        select.setText("Voltorb");
        player[count%2].setPokemon(voltorb);
        if(count%2 == 0){
            Player1Pikachu.setVisible(false);
            Player1Voltorb.setVisible(true);
            Player1Vaporeon.setVisible(false);
            Player1Squirtle.setVisible(false);
            Player1Flareon.setVisible(false);
            Player1Charizard.setVisible(false);
            player1Poke.setText("Voltorb");
            player1PokeType.setText("Electric");
            currentPoke.setText("Voltorb");
        }
        
        if(count%2 == 1){
            Player2Pikachu.setVisible(false);
            Player2Voltorb.setVisible(true);
            Player2Vaporeon.setVisible(false);
            Player2Squirtle.setVisible(false);
            Player2Flareon.setVisible(false);
            Player2Charizard.setVisible(false);
            player2Poke.setText("Voltorb");
            player2PokeType.setText("Electric");
            if(y){
                currentPoke.setText("Voltorb");
            }
        }
    }//GEN-LAST:event_VoltButtonActionPerformed
    
    /*This button makes the selection of charizard and changes every icon to
    reflect our choice
    */
    private void CharButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CharButtonActionPerformed
        // TODO add your handling code here:
        select.setText("Charizard");
        player[count%2].setPokemon(charizard);
        if(count%2 == 0){
            Player1Pikachu.setVisible(false);
            Player1Voltorb.setVisible(false);
            Player1Vaporeon.setVisible(false);
            Player1Squirtle.setVisible(false);
            Player1Flareon.setVisible(false);
            Player1Charizard.setVisible(true);
            player1Poke.setText("Charizard");
            player1PokeType.setText("Fire");
            currentPoke.setText("Charizard");
        }
        
        if(count%2 == 1){
            Player2Pikachu.setVisible(false);
            Player2Voltorb.setVisible(false);
            Player2Vaporeon.setVisible(false);
            Player2Squirtle.setVisible(false);
            Player2Flareon.setVisible(false);
            Player2Charizard.setVisible(true);
            player2Poke.setText("Charizard");
            player2PokeType.setText("Fire");
            if(y){
                currentPoke.setText("Charizard");
            }
        }
    }//GEN-LAST:event_CharButtonActionPerformed

    /*This button makes the selection of flareon and changes every icon to
    reflect our choice
    */
    private void FlarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlarButtonActionPerformed
        // TODO add your handling code here:
        select.setText("Flareon");
        player[count%2].setPokemon(flareon);
        if(count%2 == 0){
            Player1Pikachu.setVisible(false);
            Player1Voltorb.setVisible(false);
            Player1Vaporeon.setVisible(false);
            Player1Squirtle.setVisible(false);
            Player1Flareon.setVisible(true);
            Player1Charizard.setVisible(false);
            player1Poke.setText("Flareon");
            player1PokeType.setText("Fire");
            currentPoke.setText("Flareon");
        }
        
        if(count%2 == 1){
            Player2Pikachu.setVisible(false);
            Player2Voltorb.setVisible(false);
            Player2Vaporeon.setVisible(false);
            Player2Squirtle.setVisible(false);
            Player2Flareon.setVisible(true);
            Player2Charizard.setVisible(false);
            player2Poke.setText("Flareon");
            player2PokeType.setText("Fire");
            if(y){
                currentPoke.setText("Flareon");
            }
        }
    }//GEN-LAST:event_FlarButtonActionPerformed

    /*This button makes the selection of squirtle and changes every icon to
    reflect our choice
    */
    private void SquButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SquButtonActionPerformed
        // TODO add your handling code here:
        select.setText("Squirtle");
        player[count%2].setPokemon(squirtle);
        if(count%2 == 0){
            Player1Pikachu.setVisible(false);
            Player1Voltorb.setVisible(false);
            Player1Vaporeon.setVisible(false);
            Player1Squirtle.setVisible(true);
            Player1Flareon.setVisible(false);
            Player1Charizard.setVisible(false);
            player1Poke.setText("Squirtle");
            player1PokeType.setText("Water");
            currentPoke.setText("Squirtle");
        }
        
        if(count%2 == 1){
            Player2Pikachu.setVisible(false);
            Player2Voltorb.setVisible(false);
            Player2Vaporeon.setVisible(false);
            Player2Squirtle.setVisible(true);
            Player2Flareon.setVisible(false);
            Player2Charizard.setVisible(false);
            player2Poke.setText("Squirtle");
            player2PokeType.setText("Water");
            if(y){
                currentPoke.setText("Squirtle");
            }
        }
    }//GEN-LAST:event_SquButtonActionPerformed

    /*This button makes the selection of vaporeon and changes every icon to
    reflect our choice
    */
    private void VapoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VapoButtonActionPerformed
        // TODO add your handling code here:
        select.setText("Vaporeon");
        player[count%2].setPokemon(vaporeon);
        if(count%2 == 0){
            Player1Pikachu.setVisible(false);
            Player1Voltorb.setVisible(false);
            Player1Vaporeon.setVisible(true);
            Player1Squirtle.setVisible(false);
            Player1Flareon.setVisible(false);
            Player1Charizard.setVisible(false);
            player1Poke.setText("Vaporeon");
            player1PokeType.setText("Water");
            currentPoke.setText("Vaporeon");
        }
        
        if(count%2 == 1){
            Player2Pikachu.setVisible(false);
            Player2Voltorb.setVisible(false);
            Player2Vaporeon.setVisible(true);
            Player2Squirtle.setVisible(false);
            Player2Flareon.setVisible(false);
            Player2Charizard.setVisible(false);
            player2Poke.setText("Vaporeon");
            player2PokeType.setText("Water");
            if(y){
                currentPoke.setText("Vaporeon");
            }
        }
    }//GEN-LAST:event_VapoButtonActionPerformed

    private void player1HPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player1HPActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_player1HPActionPerformed

    /*This function simulates an attack from a pokemon to another pokemon,
    and reflects it in the other player's health bar
    */
    private void lightAttackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lightAttackButtonActionPerformed
        // TODO add your handling code here
        count++;
        if(count%2 == 0){
            player[1].loseHealth((player[0].lightAttack()));
            pokeName.setText(player[0].pName());
            player2HP.setText(player[1].gHealth());
            playerTurn.setText("Player " + 2);
            currentPoke.setText(player[1].pName());
        } else if(count%2 == 1){
            player[0].loseHealth((player[1].lightAttack()));
            pokeName.setText(player[1].pName());
            player1HP.setText(player[0].gHealth());
            playerTurn.setText("Player " + 1);
            currentPoke.setText(player[0].pName());
        }
        typeAttack.setText("Light Attack");
        follow.setVisible(true);
        sPokButton.setEnabled(true);
        /*The block below changes the size of the health bar*/
        if(player[0].getHealth() < 76 && player[0].getHealth() > 50){
            Player175.setVisible(true);
        } else if(player[0].getHealth() <= 50 && player[0].getHealth() > 26){
            Player175.setVisible(false);
            Player150.setVisible(true);
        } else if(player[0].getHealth() <= 25 && player[0].getHealth() > 0){
            Player175.setVisible(false);
            Player150.setVisible(false);
            Player125.setVisible(true);
        } else if(player[0].getHealth() <= 0){
            Player175.setVisible(false);
            Player150.setVisible(false);
            Player125.setVisible(false);
            Player10.setVisible(true);
        }
        if(player[1].getHealth() < 76 && player[1].getHealth() > 50){
            Player275.setVisible(true);
        } else if(player[1].getHealth() <= 50 && player[1].getHealth() > 26){
            Player275.setVisible(false);
            Player250.setVisible(true);
        } else if(player[1].getHealth() <= 25 && player[1].getHealth() > 0){
            Player275.setVisible(false);
            Player250.setVisible(false);
            Player225.setVisible(true);
        } else if(player[1].getHealth() <= 0){
            Player275.setVisible(false);
            Player250.setVisible(false);
            Player225.setVisible(false);
            Player20.setVisible(true);
        }
        /*Disable buttons so no weird things happen*/
        lightAttackButton.setEnabled(false);
        heavyAttackButton.setEnabled(false);
        sPokButton.setEnabled(false);
        forfeitButton.setEnabled(false);
    }//GEN-LAST:event_lightAttackButtonActionPerformed

    /*This button simulates a heavy attack by a pokemon*/
    private void heavyAttackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heavyAttackButtonActionPerformed
        // TODO add your handling code here:
        count++;
        if(count%2 == 0){
            player[1].loseHealth((player[0].heavyAttack()));
            pokeName.setText(player[0].pName());
            player2HP.setText(player[1].gHealth());
            playerTurn.setText("Player " + 2);
            currentPoke.setText(player[1].pName());
        } else if(count%2 == 1){
            player[0].loseHealth((player[1].heavyAttack()));
            pokeName.setText(player[1].pName());
            player1HP.setText(player[0].gHealth());
            playerTurn.setText("Player " + 1);
            currentPoke.setText(player[0].pName());
        }
        typeAttack.setText("Heavy Attack");
        follow.setVisible(true);
        sPokButton.setEnabled(true);
       if(player[0].getHealth() < 76 && player[0].getHealth() > 50){
            Player175.setVisible(true);
        } else if(player[0].getHealth() <= 50 && player[0].getHealth() > 26){
            Player175.setVisible(false);
            Player150.setVisible(true);
        } else if(player[0].getHealth() <= 25 && player[0].getHealth() > 0){
            Player175.setVisible(false);
            Player150.setVisible(false);
            Player125.setVisible(true);
        } else if(player[0].getHealth() <= 0){
            Player175.setVisible(false);
            Player150.setVisible(false);
            Player125.setVisible(false);
            Player10.setVisible(true);
        }
        if(player[1].getHealth() < 76 && player[1].getHealth() > 50){
            Player275.setVisible(true);
        } else if(player[1].getHealth() <= 50 && player[1].getHealth() > 26){
            Player275.setVisible(false);
            Player250.setVisible(true);
        } else if(player[1].getHealth() <= 25 && player[1].getHealth() > 0){
            Player275.setVisible(false);
            Player250.setVisible(false);
            Player225.setVisible(true);
        } else if(player[1].getHealth() <= 0){
            Player275.setVisible(false);
            Player250.setVisible(false);
            Player225.setVisible(false);
            Player20.setVisible(true);
        }
        lightAttackButton.setEnabled(false);
        heavyAttackButton.setEnabled(false);
        sPokButton.setEnabled(false);
        forfeitButton.setEnabled(false);
    }//GEN-LAST:event_heavyAttackButtonActionPerformed

    private void followOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_followOKActionPerformed
        // TODO add your handling code here:
        /*The if block below checks if any player has won*/
        if (hasWon()){
            BattleUI.setVisible(false);
            winUI.setVisible(true);
        } else{
            follow.setVisible(false);
        }
        /*If nobody has won, buttons will be re-enabled*/
        lightAttackButton.setEnabled(true);
        heavyAttackButton.setEnabled(true);
        sPokButton.setEnabled(true);
        forfeitButton.setEnabled(true);
    }//GEN-LAST:event_followOKActionPerformed

    public boolean hasWon(){
        if(player[0].getHealth() <= 0){
            wPlayer.setText("Player 2");//checks if player 2 has won
            return true;
        } else if(player[1].getHealth() <= 0){
            wPlayer.setText("Player 1");//checks if player 1 has won
            return true;
        } else{
            return false;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PokeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PokeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PokeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PokeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //PokeSelectUI.setVisible(false);
        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PokeGUI().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BattleUI;
    private javax.swing.JButton CharButton;
    private javax.swing.JButton FlarButton;
    private javax.swing.JButton PikaButton;
    private javax.swing.JLabel Player10;
    private javax.swing.JLabel Player125;
    private javax.swing.JLabel Player150;
    private javax.swing.JLabel Player175;
    private javax.swing.JLabel Player1Charizard;
    private javax.swing.JLabel Player1Flareon;
    private javax.swing.JLabel Player1Pikachu;
    private javax.swing.JLabel Player1Squirtle;
    private javax.swing.JLabel Player1Vaporeon;
    private javax.swing.JLabel Player1Voltorb;
    private javax.swing.JLabel Player20;
    private javax.swing.JLabel Player225;
    private javax.swing.JLabel Player250;
    private javax.swing.JLabel Player275;
    private javax.swing.JLabel Player2Charizard;
    private javax.swing.JLabel Player2Flareon;
    private javax.swing.JLabel Player2Pikachu;
    private javax.swing.JLabel Player2Squirtle;
    private javax.swing.JLabel Player2Vaporeon;
    private javax.swing.JLabel Player2Voltorb;
    private javax.swing.JPanel PokeSelectUI;
    private javax.swing.JButton SquButton;
    private javax.swing.JButton VapoButton;
    private javax.swing.JButton VoltButton;
    private javax.swing.JTextField currentPoke;
    private javax.swing.JTextField effective;
    private javax.swing.JButton exit;
    private javax.swing.JPanel follow;
    private javax.swing.JButton followOK;
    private javax.swing.JButton forfeitButton;
    private javax.swing.JTextField grats;
    private javax.swing.JButton heavyAttackButton;
    private javax.swing.JButton lightAttackButton;
    private javax.swing.JLabel mainBattle;
    private javax.swing.JButton mainButton;
    private javax.swing.JLabel mainImage;
    private javax.swing.JPanel mainUI;
    private javax.swing.JButton okSelect;
    private javax.swing.JTextField pTurn;
    private javax.swing.JButton play;
    private javax.swing.JTextField player1HP;
    private javax.swing.JTextField player1Poke;
    private javax.swing.JTextField player1PokeType;
    private javax.swing.JTextField player2HP;
    private javax.swing.JTextField player2Poke;
    private javax.swing.JTextField player2PokeType;
    private javax.swing.JTextField playerTurn;
    private javax.swing.JTextField pokeName;
    private javax.swing.JButton sPokButton;
    private javax.swing.JTextField select;
    private javax.swing.JTextField typeAttack;
    private javax.swing.JTextField used;
    private javax.swing.JTextField wPlayer;
    private javax.swing.JPanel winUI;
    private javax.swing.JTextField won;
    // End of variables declaration//GEN-END:variables
}
